x-deploy-policy: &x-deploy-policy
  mode: global
  resources:
    limits:
      memory: 256M
    reservations:
      memory: 64M

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

networks:
  dockerswarm_monitoring:
    name: dockerswarm_monitoring
    external: true

configs:
  promtail-config:
    file: configs/promtail.yaml

services:
  promtail:
    image:  grafana/promtail:${PROMTAIL_VERSION:-latest}
    command: -config.file=/etc/promtail/config.yml
    networks:
      - dockerswarm_monitoring
    ports:
      - ${PROMTAIL_PORT:-9080}:9080
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: promtail-config
        target: /etc/promtail/config.yml
    depends_on:
      - loki
    deploy: 
      <<: *x-deploy-policy
      labels:
        io.prometheus.enable: "true"
    logging: *x-default-logging
