# https://grafana.com/docs/loki/latest/clients/promtail/configuration/
# https://docs.docker.com/engine/api/v1.41/#operation/ContainerList
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - # The tenant ID used by default to push logs to Loki. If omitted or empty
    # it assumes Loki is running in single-tenant mode and no X-Scope-OrgID header
    # is sent.
    tenant_id: demo
    url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  # See https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#docker_sd_config
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        # filters:
        #   - name: label
        #     values: ["logging=promtail"]
    relabel_configs:
      - source_labels:
          - __meta_docker_container_label_com_docker_swarm_node_id
        target_label: __host__

      - action: replace
        regex: '/(.*)'
        source_labels:
          - __meta_docker_container_name
        target_label: container

      - action: labeldrop
        regex: '__meta_docker_container_label_.+(mounts).+'

      - action: labelmap
        regex: __meta_docker_(container_label_.+)
      - action: labelmap
        regex: __meta_docker_container_label_com_(docker_stack_.+)

      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_docker_container_label_com_docker_stack_namespace
          - container
        target_label: job

      - action: replace
        source_labels:
          - __meta_docker_container_label_com_docker_stack_namespace
        target_label: namespace
      
      - replacement: /var/log/containers/*$1/*.log
        separator: /
        source_labels:
          - __meta_docker_container_id
          - container
        target_label: __path__
